// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrjsonumxdrcfpkaneyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyanNvbnVteGRyY2Zwa2FuZXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTYxNTgsImV4cCI6MjA2MzY5MjE1OH0.Lz8aBwUeT1kVgFOst-9y90TPqZbOUFIi5pIgiAUiS1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);